### ISSUE TITLE
Can you add to README all the different things we can enable via config?

### ISSUE THREAD

**Issue by webcoderz** [SecretiveShell/MCP-Bridge#9]
document all the accepted config things we can enable

**Comment by SecretiveShell** [comment]
Sure, this is probably good to have.

```json
{
    "inference_server": {
        "base_url": "http://localhost:8000/v1",
        "api_key": "None"
    },
    "mcp_servers": {
        "fetch": {
            "command": "uvx",
            "args": [
                "mcp-server-fetch"
            ]
        }
    },
    "network": {
        "host": "0.0.0.0",
        "port": 9090
    },
    "logging": {
        "log_level": "DEBUG"
    }
}
```

has basically every option that you can edit. do not change the network options unless you are not running in docker as this will break the default port forwarding rules.

I can add this to the readme.

It would be cool to have pydantic export a json schema so that you get autocomplete when editing the config in vscode, but as of right now that is a low priority - I want to finish the streaming responses first ideally.

**Comment by webcoderz** [comment]
yea thats great idea, thanks
